//! GPU kernel integration - connects compiled PTX to tensor operations
//!
//! This module loads kernels compiled by build.rs and launches them via cudarc

#![cfg(feature = "cuda")]

use std::collections::HashMap;
use std::sync::Arc;
use cudarc::driver::{CudaDevice, CudaSlice, CudaFunction, LaunchConfig};
use cudarc::nvrtc::Ptx;

/// Kernel manager - loads and caches compiled kernels
pub struct KernelManager {
    device: Arc<CudaDevice>,
    functions: HashMap<String, CudaFunction>,
}

impl KernelManager {
    /// Create new kernel manager and load all built-in kernels
    pub fn new(device: Arc<CudaDevice>) -> Result<Self, String> {
        let mut mgr = Self {
            device,
            functions: HashMap::new(),
        };
        
        // Load built-in kernels from PTX generated by build.rs
        mgr.load_builtin_kernels()?;
        
        Ok(mgr)
    }

    /// Load built-in kernels from compiled PTX
    fn load_builtin_kernels(&mut self) -> Result<(), String> {
        // PTX code generated at build time by build.rs
        let ptx = include_str!(concat!(env!("OUT_DIR"), "/kernels.ptx"));
        
        let ptx = Ptx::from_src(ptx)
            .map_err(|e| format!("Failed to parse PTX: {}", e))?;
        
        // All kernel names
        let kernel_names = vec![
            // Element-wise
            "vecadd_f32", "sub_f32", "mul_f32", "div_f32", "scale_f32",
            // Matrix
            "matmul_naive_f32", "matvec_f32", "transpose_f32",
            // Activation
            "relu_f32", "silu_f32", "gelu_f32", "sigmoid_f32", "tanh_f32",
            // Normalization
            "rms_norm_f32", "layer_norm_f32",
            // Attention
            "attention_forward_f32", "softmax_f32",
        ];
        
        self.device.load_ptx(ptx, "kernels", &kernel_names)
            .map_err(|e| format!("Failed to load PTX: {}", e))?;
        
        // Cache function handles
        for name in &kernel_names {
            if let Some(func) = self.device.get_func("kernels", name) {
                self.functions.insert(name.to_string(), func);
            } else {
                eprintln!("Warning: Kernel {} not found in PTX", name);
            }
        }
        
        Ok(())
    }

    /// Get kernel function by name
    fn get_kernel(&self, name: &str) -> Option<&CudaFunction> {
        self.functions.get(name)
    }

    /// Launch vector addition: c = a + b
    pub fn launch_vecadd(
        &self,
        a: &CudaSlice<f32>,
        b: &CudaSlice<f32>,
        c: &mut CudaSlice<f32>,
        n: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("vecadd_f32")
            .ok_or("Kernel vecadd_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(n as u32);
        
        unsafe {
            func.launch(cfg, (a, b, c, n as i32))
                .map_err(|e| format!("vecadd launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch vector subtraction: c = a - b
    pub fn launch_sub(
        &self,
        a: &CudaSlice<f32>,
        b: &CudaSlice<f32>,
        c: &mut CudaSlice<f32>,
        n: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("sub_f32")
            .ok_or("Kernel sub_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(n as u32);
        
        unsafe {
            func.launch(cfg, (a, b, c, n as i32))
                .map_err(|e| format!("sub launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch element-wise multiply: c = a * b
    pub fn launch_mul(
        &self,
        a: &CudaSlice<f32>,
        b: &CudaSlice<f32>,
        c: &mut CudaSlice<f32>,
        n: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("mul_f32")
            .ok_or("Kernel mul_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(n as u32);
        
        unsafe {
            func.launch(cfg, (a, b, c, n as i32))
                .map_err(|e| format!("mul launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch element-wise division: c = a / b
    pub fn launch_div(
        &self,
        a: &CudaSlice<f32>,
        b: &CudaSlice<f32>,
        c: &mut CudaSlice<f32>,
        n: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("div_f32")
            .ok_or("Kernel div_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(n as u32);
        
        unsafe {
            func.launch(cfg, (a, b, c, n as i32))
                .map_err(|e| format!("div launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch scale: out = in * scale
    pub fn launch_scale(
        &self,
        input: &CudaSlice<f32>,
        output: &mut CudaSlice<f32>,
        scale: f32,
        n: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("scale_f32")
            .ok_or("Kernel scale_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(n as u32);
        
        unsafe {
            func.launch(cfg, (input, output, scale, n as i32))
                .map_err(|e| format!("scale launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch matrix multiplication: C = A * B
    pub fn launch_matmul_naive(
        &self,
        a: &CudaSlice<f32>,
        b: &CudaSlice<f32>,
        c: &mut CudaSlice<f32>,
        m: usize,
        n: usize,
        k: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("matmul_naive_f32")
            .ok_or("Kernel matmul_naive_f32 not loaded")?;
        
        let block_size = 16;
        let grid_x = ((m + block_size - 1) / block_size) as u32;
        let grid_y = ((n + block_size - 1) / block_size) as u32;
        
        let cfg = LaunchConfig {
            grid_dim: (grid_x, grid_y, 1),
            block_dim: (block_size as u32, block_size as u32, 1),
            shared_mem_bytes: 0,
        };
        
        unsafe {
            func.launch(cfg, (a, b, c, m as i32, n as i32, k as i32))
                .map_err(|e| format!("matmul launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch ReLU activation
    pub fn launch_relu(
        &self,
        input: &CudaSlice<f32>,
        output: &mut CudaSlice<f32>,
        n: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("relu_f32")
            .ok_or("Kernel relu_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(n as u32);
        
        unsafe {
            func.launch(cfg, (input, output, n as i32))
                .map_err(|e| format!("relu launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch SiLU activation
    pub fn launch_silu(
        &self,
        input: &CudaSlice<f32>,
        output: &mut CudaSlice<f32>,
        n: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("silu_f32")
            .ok_or("Kernel silu_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(n as u32);
        
        unsafe {
            func.launch(cfg, (input, output, n as i32))
                .map_err(|e| format!("silu launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch GELU activation
    pub fn launch_gelu(
        &self,
        input: &CudaSlice<f32>,
        output: &mut CudaSlice<f32>,
        n: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("gelu_f32")
            .ok_or("Kernel gelu_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(n as u32);
        
        unsafe {
            func.launch(cfg, (input, output, n as i32))
                .map_err(|e| format!("gelu launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch Sigmoid activation
    pub fn launch_sigmoid(
        &self,
        input: &CudaSlice<f32>,
        output: &mut CudaSlice<f32>,
        n: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("sigmoid_f32")
            .ok_or("Kernel sigmoid_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(n as u32);
        
        unsafe {
            func.launch(cfg, (input, output, n as i32))
                .map_err(|e| format!("sigmoid launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch Tanh activation
    pub fn launch_tanh(
        &self,
        input: &CudaSlice<f32>,
        output: &mut CudaSlice<f32>,
        n: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("tanh_f32")
            .ok_or("Kernel tanh_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(n as u32);
        
        unsafe {
            func.launch(cfg, (input, output, n as i32))
                .map_err(|e| format!("tanh launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch RMS normalization
    pub fn launch_rms_norm(
        &self,
        input: &CudaSlice<f32>,
        weight: &CudaSlice<f32>,
        output: &mut CudaSlice<f32>,
        num_rows: usize,
        num_cols: usize,
        eps: f32,
    ) -> Result<(), String> {
        let func = self.get_kernel("rms_norm_f32")
            .ok_or("Kernel rms_norm_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(num_rows as u32);
        
        unsafe {
            func.launch(cfg, (input, weight, output, num_rows as i32, num_cols as i32, eps))
                .map_err(|e| format!("rms_norm launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch Layer normalization
    pub fn launch_layer_norm(
        &self,
        input: &CudaSlice<f32>,
        weight: &CudaSlice<f32>,
        bias: &CudaSlice<f32>,
        output: &mut CudaSlice<f32>,
        num_rows: usize,
        num_cols: usize,
        eps: f32,
    ) -> Result<(), String> {
        let func = self.get_kernel("layer_norm_f32")
            .ok_or("Kernel layer_norm_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(num_rows as u32);
        
        unsafe {
            func.launch(cfg, (input, weight, bias, output, num_rows as i32, num_cols as i32, eps))
                .map_err(|e| format!("layer_norm launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Launch softmax
    pub fn launch_softmax(
        &self,
        input: &CudaSlice<f32>,
        output: &mut CudaSlice<f32>,
        num_rows: usize,
        num_cols: usize,
    ) -> Result<(), String> {
        let func = self.get_kernel("softmax_f32")
            .ok_or("Kernel softmax_f32 not loaded")?;
        
        let cfg = LaunchConfig::for_num_elems(num_rows as u32);
        
        unsafe {
            func.launch(cfg, (input, output, num_rows as i32, num_cols as i32))
                .map_err(|e| format!("softmax launch failed: {}", e))?;
        }
        
        Ok(())
    }

    /// Check if a kernel is available
    pub fn has_kernel(&self, name: &str) -> bool {
        self.functions.contains_key(name)
    }

    /// Get list of loaded kernels
    pub fn loaded_kernels(&self) -> Vec<&str> {
        self.functions.keys().map(|s| s.as_str()).collect()
    }
}

/// GPU operations using kernels
pub struct GpuOps {
    _device: Arc<CudaDevice>,
}

impl GpuOps {
    pub fn new(device: Arc<CudaDevice>) -> Result<Self, String> {
        Ok(Self { _device: device })
    }
}
